[project]
name = "pdf-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.42.30",
    "chromadb>=1.4.1",
    "dotenv>=0.9.9",
    "langchain>=0.3.27",
    "langchain-anthropic>=0.3.22",
    "langchain-aws>=0.2.35",
    "langchain-chroma>=0.2.6",
    "langchain-community>=0.3.31",
    "langchain-openai>=0.3.35",
    "langchain-text-splitters>=0.3.11",
    "onnxruntime==1.19.2",
    "pypdf>=6.6.0",
    "sentence-transformers>=5.1.2",
]
